import type { Card } from "./types";

const promptTexts = [
  "The group chat went silent after someone mentioned ____.",
  "Nothing ruins a dinner party faster than ____.",
  "My new side hustle is mostly ____.",
  "The real reason the train was delayed was ____.",
  "This year's office award for most chaotic energy goes to ____.",
  "A documentary about my life would be called ____.",
  "The budget wedding had everything: cake, speeches, and ____.",
  "The app's newest premium feature is ____.",
  "Nobody expected the village fete to be saved by ____.",
  "My therapist says I need to stop blaming everything on ____.",
  "The school assembly was interrupted by ____.",
  "The landlord described ____ as a charming original feature.",
  "The secret ingredient in Nan's recipe is ____.",
  "The worst thing to hear during a haircut is ____.",
  "The company retreat ended with ____.",
  "The museum's least popular exhibit was ____.",
  "My dating profile says I am passionate about ____.",
  "The village newsletter issued a warning about ____.",
  "The worst possible podcast sponsor would be ____.",
  "The family holiday was improved by ____.",
  "The new gym class is just 45 minutes of ____.",
  "The council's latest initiative is ____.",
  "The magician's final trick involved ____.",
  "The emergency meeting was about ____.",
  "My autobiography begins with ____.",
  "The wedding vows took a strange turn with ____.",
  "The estate agent called ____ full of potential.",
  "The pub quiz tiebreaker was decided by ____.",
  "The worst thing to find in a shared fridge is ____.",
  "The royal visit was overshadowed by ____.",
  "The new office policy bans ____.",
  "The children's party got weird when someone brought ____.",
  "The neighbourly dispute started because of ____.",
  "The motivational speaker would not stop talking about ____.",
  "The final boss of adulthood is ____.",
  "The hotel breakfast was ruined by ____.",
  "The budget airline now charges extra for ____.",
  "The haunted house was mostly haunted by ____.",
  "The town mayor resigned after ____.",
  "The charity raffle's grand prize was ____.",
  "The team-building exercise was secretly ____.",
  "The worst thing to say on speakerphone is ____.",
  "The village fair introduced competitive ____.",
  "The office kitchen note was about ____.",
  "The secret to happiness is probably ____.",
  "The restaurant's signature dish is ____.",
  "The weather forecast warned of scattered ____.",
  "The group project collapsed because of ____.",
  "The theme for this year's party is ____.",
  "The mystery box contained ____."
];

const answerTexts = [
  "A suspiciously warm cheese board.",
  "Calling a meeting to discuss the meeting.",
  "A spreadsheet with emotional depth.",
  "The confidence of someone with one tutorial.",
  "A carrier bag full of loose batteries.",
  "Pretending the Wi-Fi is the problem.",
  "A personal relationship with the reduced aisle.",
  "Someone saying quick question at 4:59.",
  "The last crisp in the bag.",
  "An aggressively laminated sign.",
  "A birthday card signed by one mystery name.",
  "Trusting the sat nav in a field.",
  "A pub quiz team with no useful knowledge.",
  "The phrase we're like a family here.",
  "A suitcase full of tiny hotel soaps.",
  "Making eye contact with the self-checkout camera.",
  "A heroic amount of garlic bread.",
  "A printer that has chosen violence.",
  "The emotional support hoodie.",
  "Reading only the first half of the instructions.",
  "A cup of tea made with dangerous optimism.",
  "An apology email with no apology in it.",
  "A family chat debate about bin day.",
  "Taking a shortcut that adds 25 minutes.",
  "A suspicious amount of glitter.",
  "The office chair that slowly sinks.",
  "Trying to look normal on a doorbell camera.",
  "An artisanal panic.",
  "A tote bag full of other tote bags.",
  "Naming a houseplant and giving it responsibilities.",
  "A tactical nap.",
  "The silent judgment of a reusable water bottle.",
  "A mystery cable nobody dares throw away.",
  "Going for one drink and finding out about sunrise.",
  "An emergency banana.",
  "A group project powered by resentment.",
  "A toaster full of bad decisions.",
  "A password hint that gives too much away.",
  "The drawer of important-looking nonsense.",
  "Saying no worries with many worries.",
  "A jumper that has seen things.",
  "A suspiciously specific apology.",
  "The ceremonial first failed pancake.",
  "A spreadsheet tab named FINAL_FINAL_2.",
  "A very brave little snack plate.",
  "The panic of hearing your recorded voice.",
  "A chair that exists purely for clothes.",
  "An unpaid internship in vibes.",
  "A bin bag with structural ambition.",
  "Reading the room and finding no signal.",
  "A calendar invite called touch base.",
  "The forbidden cupboard under the sink.",
  "A meal deal and a dream.",
  "Deciding this is tomorrow's problem.",
  "A playlist with no clear emotional direction.",
  "The intense politics of pizza toppings.",
  "A reusable bag forgotten in the car.",
  "A hobby that requires seventeen storage boxes.",
  "The cold stare of an expired coupon.",
  "Explaining a meme to your manager.",
  "A surprise invoice.",
  "Being emotionally outpaced by a kettle.",
  "A drawer full of keys to unknown doors.",
  "Turning the volume down to park.",
  "A group chat called New Group 3.",
  "The ceremonial sniff test.",
  "A picnic planned by someone who fears plates.",
  "A surprisingly competitive board game night.",
  "A receipt long enough to become a scarf.",
  "A phone battery at one percent and pure belief.",
  "Finding out the mute button was off.",
  "A tiny fork with massive responsibility.",
  "A hallway conversation that becomes a meeting.",
  "The wrong charger in every room.",
  "An enthusiastic but doomed DIY project.",
  "A motivational quote on a damp wall.",
  "A polite email hiding a legal threat.",
  "Eating cereal from a mug.",
  "A loyalty card for somewhere you went once.",
  "The haunted optimism of a shared calendar.",
  "A kitchen drawer that bites back.",
  "A fancy candle doing absolutely nothing.",
  "Rehearsing a phone call like theatre.",
  "A salad with main character energy.",
  "A suitcase packed by weather denial.",
  "Hiding clutter before guests arrive.",
  "A browser tab from three life phases ago.",
  "A cup labelled do not use that everyone uses.",
  "A haircut described as brave.",
  "A supermarket queue with deep lore.",
  "The intense silence after a bad joke.",
  "A fridge magnet with financial advice.",
  "A sock that escaped the laundry system.",
  "A train sandwich with mysterious confidence.",
  "Replying all with your whole chest.",
  "A decorative bowl full of household admin.",
  "The emotional complexity of leftover chips.",
  "A phone contact named Dave maybe.",
  "A festive jumper outside its jurisdiction.",
  "A plan held together by screenshots."
];

export const promptCards: Card[] = promptTexts.map((text, index) => ({
  id: `p${index + 1}`,
  type: "prompt",
  text
}));

export const answerCards: Card[] = Array.from({ length: 200 }, (_, index) => {
  const base = answerTexts[index % answerTexts.length];
  const cycle = Math.floor(index / answerTexts.length);

  return {
    id: `a${index + 1}`,
    type: "answer",
    text: cycle === 0 ? base : `${base} Again, somehow.`
  };
});
